FROM python:3.12-slim

WORKDIR /home/app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
# Folders voor webapp
COPY static ./static
COPY templates ./templates
COPY flask_app_loginV2.py .

EXPOSE 5050

CMD ["python", "flask_app_loginV2.py"]
 